### ISSUE TITLE
ida 9 pro  not working

### ISSUE THREAD

**Issue by mr00ff** [kweatherman/yara4ida#5]
Thank you for sharing. I would like to give you feedback. There is no ida64.dll in ida 9 version. I suspect that it cannot work because this module cannot be found. It can be used in version 8.3. If you can look forward to your repair  : P

ida version : 9.0.240925 v2

![image](https://github.com/user-attachments/assets/7131dcc0-73a1-4816-ab02-288ef8151229)

**Comment by kweatherman** [comment]
I see. I doubt "ida64.dll" is the problem since it would break all pre version 9 plugins if it wasn't there.
I see like you highlighted "yara4ida64.dll" that didn't actually load.

Also I see you are using your native (or just alternate) windows language.
IF you are using file paths with other than ASCII chars, that will most likely be a problem.
And I would think it would be a problem with many other plugins, scripts, etc.

I am aware there are other character sets out there, thus in file paths for some people, but I only use ASCII character set APIs.
Not using WCHAR or UTF-8 for my path strings.

Do any of your IDA paths have non ASCII characters?

**Comment by kweatherman** [comment]
Also see the pull request: https://github.com/kweatherman/yara4ida/pull/4
I thought by now I would have IDA 9, but still stuck with 8 for the time being.
I need to try his patch.
